name: Deploy branch to Sandbox
run-name: Deploy branch ${{ github.ref_name }} to Sandbox

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Nom de la branche à déployer'
        required: true
        default: 'main'

jobs:
  deploy_api:
    permissions:
      contents: write
      repository-projects: write
      actions: write  
    uses: Nassim952/mulesoft_cicd/.github/workflows/api_deploy.yaml@main
    with:
      ENV: sandbox
      BRANCH: ${{ inputs.branch }}
      WORKERS: ${{ vars.WORKERS }}
      VCORES: ${{ vars.VCORES }}
      APP_NAME: "eapi-weather-app-sandbox"
    secrets: inherit
