name: Deploy TAG to Dev
run-name: Deploy tag ${{ github.ref_name }} to Dev

on:
  workflow_dispatch:
    inputs:
      jira_ticket:
        description: 'Jira ticket number'
        required: false
        default: ''

jobs:
  deploy_api:
    uses: esgi-corp/mulesoft_cicd/.github/workflows/api_deploy.yaml@main
    with:
      env: dev
      branch: ${{ github.ref_name }}
      jira_ticket: ${{ github.event.inputs.jira_ticket }}
      workers: ${{ vars.WORKERS }}
      vcores: ${{ vars.VCORES }} 
      app_name: "eapi-weather-app"
      repo_props_name: "mulesoft-eapi-weather-properties"
    secrets: inherit