name: Deploy branch to Sandbox
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Nom de la branche à déployer'
        required: true
        default: 'main'

jobs:
  deploy_api:
    uses: Nassim952/mulesoft_cicd/.github/workflows/api_deploy.yaml@main
    with:
      ENV: sandbox
      BRANCH: ${{ github.event.inputs.branch }}
      WORKERS: ${{ vars.WORKERS }}
      VCORES: ${{ vars.VCORES }}
      APP_NAME: "eapi-weather-app-sandbox"
    secrets: inherit
