name: Deploy TAG to Prd
run-name: Deploy tag ${{ github.ref_name }} to Prd

on:
  workflow_dispatch:

jobs:
  deploy_api:
    uses: Nassim952/mulesoft_cicd/.github/workflows/api_deploy.yaml@main
    with:
      env: prd
      branch: ${{ github.ref_name }}
      workers: ${{ vars.WORKERS }}
      vcores: ${{ vars.VCORES }} 
      app_name: "eapi-weather-app-prd"
    secrets: inherit